### ISSUE TITLE
404 Not Found when trying to install from Github

### ISSUE THREAD

**Issue by mpaperno** [mpaperno/skia-canvas#1]
[_Originally posted by @arhip144 in https://github.com/samizdatco/skia-canvas/issues/150#issuecomment-1751419948_]

              npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/mpaperno/skia-canvas/releases/download/1.1.1-mp/win32-x64-napi-v6-unknown.tar.gz

I think "https://github.com/mpaperno/skia-canvas/releases/download/v1.1.1-mp/win32-x64-napi-v6-unknown.tar.gz" is correct
v1.1.1
not just 1.1.1

**Comment by mpaperno** [comment]
@arhip144 Hi Anton, sorry about that.  Strange that it worked for me with my project... not sure why.  Anyway, could you try again with the latest fix?

Thanks,
-Max

**Comment by arhip144** [comment]
> @arhip144 Hi Anton, sorry about that. Strange that it worked for me with my project... not sure why. Anyway, could you try again with the latest fix?
> 
> Thanks, -Max

It works, thanks

**Comment by mpaperno** [comment]
That's good news, thanks for letting me know.

(Fixed in https://github.com/mpaperno/skia-canvas/commit/53e11a022e70b888d48dadec226f69fc6a5d7758)
